# Generated by Django 4.2.6 on 2023-10-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_post_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
